use_frameworks!

platform :ios, '9.0'

target 'CategoryManage_Example' do
  pod 'CategoryManage', :path => '../'

  target 'CategoryManage_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
